---
title: "Existencia y unicidad fuerte"
lang: es
format:
  html: default
  pdf:
    include-in-header:
      text: |
        \usepackage{upgreek}
    latex-engine: pdflatex
---

::: {#thm-varmues style="text-align: justify"}
Sea $(\Omega, \mathcal{F}, (\mathcal{F}_t)_{t \geq 0}, \mathbb{P})$ un espacio de probabilidad filtrado que satisface las hipótesis usuales. Consideremos la ecuación diferencial estocástica modificada (sin saltos grandes):

$$
\begin{aligned}
dZ(t) ={}& b(Z(t-)) \, dt \\
         &+ \sigma(Z(t-)) \, dB(t) \\
         &+ \int_{|x| < c} F(Z(t-), x) \, \widetilde{N}(dt, dx), \qquad t \geq 0,
\end{aligned}
$$ {#eq-sde}

con condición inicial $Z(0) = Z_0$, donde $B(t)$ es un movimiento browniano estándar unidimensional ($r=1$); $N(dt, dx)$ es una medida aleatoria de Poisson definida en $\mathbb{R}_+ \times (\mathbb{R} \setminus \{0\})$ con medida de intensidad $\nu(dx)$; $\widetilde{N}(dt, dx) = N(dt, dx) - \nu(dx)\,dt$ denota la correspondiente medida compensada; $c \in (0, \infty]$ es un umbral fijo que separa los saltos pequeños de los grandes; y $Z_0$ es una variable aleatoria $\mathcal{F}_0$-medible, independiente del ruido estocástico.

Supongamos que los coeficientes $b: \mathbb{R} \to \mathbb{R}$, $\sigma: \mathbb{R} \to \mathbb{R}$ y $F: \mathbb{R} \times \mathbb{R} \to \mathbb{R}$ son funciones medibles que satisfacen las siguientes condiciones:

#### (C1) Condición de Lipschitz:

Existe una constante $K_1 > 0$ tal que, para todo $y_1, y_2 \in \mathbb{R}$,

$$
\begin{aligned}
|b(y_1) - b(y_2)|^2 & + |\sigma(y_1) - \sigma(y_2)|^2\\ 
& + \int_{|x| < c} |F(y_1, x) - F(y_2, x)|^2 \, \nu(dx) \\
&\leq K_1 |y_1 - y_2|^2.
\end{aligned}
$$ {#eq-lipschitz}

#### (C2) Condición de crecimiento lineal:

Existe una constante $K_2 > 0$ tal que, para todo $y \in \mathbb{R}$,

$$
|b(y)|^2 + |\sigma(y)|^2 + \int_{|x| < c} |F(y, x)|^2 \, \nu(dx)
\leq K_2 \bigl(1 + |y|^2 \bigr).
$$ {#eq-3}

Bajo las hipótesis anteriores, existe una única solución fuerte $Z = (Z(t))_{t \geq 0}$ de la ecuación (@eq-sde) tal que:

-   $Z$ es un proceso adaptado y cádlág (continuo por la derecha con límites por la izquierda),
-   La solución es única casi seguramente, esto es, si $(Z')$ es otra solución, entonces $$
     \mathbb{P}\bigl(Z(t) = Z'(t) \text{ para todo } t \geq 0\bigr) = 1.
     $$ {#eq-4}
:::

::: {.proof style="text-align: justify"}
Queremos ver la existencia de una solución $Z=(Z(t))_{t\geq 0}$ para la ecuación (@eq-sde) con condición inicial $Z(0)=Z_0$. Bajo las hipótesis (@eq-lipschitz) y (@eq-3) para los coeficientes $b$, $\sigma$ y $F$. Analizaremos primero el caso cuando $\mathbb{E}[|Z_0|^2]<\infty$. Dado que la ecuación estocástica de nuestro caso posee un movimiento browniano $B$, es decir, ruido estocástico y una medida de Poisson compensada, dada por $\widetilde{N}$, para esto utilizaremos la iteración de Picard construyendo una sucesión de procesos estocásticos a partir de la condición inicial. Definiendo la suceción de la siguiente forma:

$$
    Z_0(t) :=Z_0, \, \, \forall t\geq 0.
$$

Para $n\geq 1$

$$
    \begin{aligned}
        Z_{n+1}(t) := Z_0 & +\int _0^t b(Z_n(s-))ds+\int_0^t \sigma(Z(s-))dB(s)\\ 
        & + \int_0^t \int _{|x|<c} F(Z_n(s-),x)\widetilde{N}(ds,dx).
    \end{aligned}
$$

Demostraremos que el proceso $Z_n$ es un proceso adaptado y con trayectorias Cádlág. Consideremos la diferencia $Z_1(t)-Z_0(t)$. Por la iteración de Picard tenemos:

$$
    \begin{aligned}
        Z_1(t) = Z_0(t) & + \int_0^t b(Z_0(s-))ds +\int_0^t\sigma(Z_0(s-))\\ 
        & +\int_0^t \int_{|x|<c} F(Z_0(s-),x)\widetilde{N}(ds,dx).
    \end{aligned}
$$

Dado que $Z_0(t)=Z_0$ para todo $t\geq 0$, entonces,

$$
    \begin{aligned}
        Z_1(t)-Z_0 = \int_0^t b(Z_0) ds & + \int_0^t \sigma(Z_0)dB(s)\\ 
        & + \int_0^t\int_{|x|<c} F(Z_0,x)\widetilde{N}(ds,dx). 
    \end{aligned}
$$

Considerando la desigualdad

$$
(a+b+c)^2\leq 3(a^2+b^2+c^2).
$$ {#eq-des}

Tomando valor absoulto y elevando al cuadrado la expreción anterior tenemos que

$$
    \begin{aligned}
|Z_1(t)-Z_0|^2
&= \Bigg|
      \int_0^t b(Z_0)\,ds
      + \int_0^t \sigma(Z_0)\,dB(s) \\
&\qquad\quad
      + \int_0^t\!\!\int_{|x|<c} F(Z_0,x)\,\widetilde{N}(ds,dx)
   \Bigg|^2 \\[0.3em]
&\le 3\Bigg(
      \left(\int_0^t b(Z_0)\,ds\right)^2
      + \left(\int_0^t \sigma(Z_0)\,dB(s)\right)^2 \\
&\qquad\quad
      + \left(\int_0^t\!\!\int_{|x|<c} F(Z_0,x)\,\widetilde{N}(ds,dx)\right)^2
   \Bigg).
\end{aligned}
$$

Para controlar de manera uniforme en todo el intervalo $[0,t]$ tomamos el supremo sobre todo el intervalo, además usando propiedades del supremos podemos obtener

$$
\begin{aligned}
\sup\limits_{0\leq s\leq t}|Z_1(s)-Z_0|^2
&\leq \sup\limits_{0\leq s\leq t}\Bigg(3\Bigg(
      \left(\int_0^s b(Z_0)\,ds\right)^2
      + \left(\int_0^s \sigma(Z_0)\,dB(s)\right)^2 \\
&\qquad\quad
      + \left(\int_0^s\!\!\int_{|x|<c} F(Z_0,x)\,\widetilde{N}(ds,dx)\right)^2
   \Bigg)\Bigg)\\
& = 3\Bigg(\sup\limits_{0\leq s\leq t}\left(\int_0^s b(Z_0)\,ds\right)^2 + \sup\limits_{0\leq s\leq t} \left(\int_0^s \sigma(Z_0)\,dB(s)\right)^2 \\ 
&\qquad\quad 
    + \sup\limits_{0\leq s\leq t} \left(\int_0^s\!\!\int_{|x|<c} F(Z_0,x)\,\widetilde{N}(ds,dx)\right)^2\Bigg).
\end{aligned}
$$

Tomando valor esperado de ambos lado y usando la linealidad, tenemos que

$$
\begin{aligned}
\mathbb{E}\Bigg[\sup\limits_{0\leq s\leq t}|Z_1(s)-Z_0|^2\Bigg]
& \leq \mathbb{E}\Bigg[3\Bigg(\sup\limits_{0\leq s\leq t}\left(\int_0^s b(Z_0)\,ds\right)^2\\
&\qquad   
    + \sup\limits_{0\leq s\leq t} \left(\int_0^s \sigma(Z_0)\,dB(s)\right)^2 \\ 
&\qquad\quad
    + \sup\limits_{0\leq s\leq t} \left(\int_0^s\!\!\int_{|x|<c} F(Z_0,x)\,\widetilde{N}(ds,dx)\right)^2\Bigg)\Bigg]\\
& = 3\Bigg( \mathbb{E}\Bigg[\sup\limits_{0\leq s\leq t}\left(\int_0^s b(Z_0)\,ds\right)^2\Bigg]\\ 
&\qquad
    + \mathbb{E}\Bigg[\sup\limits_{0\leq s\leq t} \left(\int_0^s \sigma(Z_0)\,dB(s)\right)^2\Bigg]\\
&\qquad\quad
    +\mathbb{E}\Bigg[\sup\limits_{0\leq s\leq t} \left(\int_0^s\!\!\int_{|x|<c} F(Z_0,x)\,\widetilde{N}(ds,dx)\right)^2\Bigg]\Bigg).
\end{aligned}
$$ {#eq-5}

Trabajaremos término por termino; así notemos que la siguiente integral es de Lebesgue

$$
    \int_0^s b(z_0)du = b(z_0) \int_0^s du = b(z_0)\cdot s
$$

Por lo tanto

$$
    \sup\limits_{0\leq s\leq t}\Bigg(\int_0^s b(Z_0)du\Bigg)^2=\sup\limits_{0\leq s\leq t}(b(Z_0)\cdot s)^2=\sup\limits_{0\leq s\leq t} b(Z_0)^2\cdot s^2= b(Z_0)^2\cdot t^2.
$$

Consideremos ahora el proceso

$$
    M(s):=\int_0^s \sigma(Z_0)dB(u).
$$ {#eq-mart}

Afirmamos que dicho proceso es una martingala, pues al ser $Z_0$ constante esto implica que $\sigma(Z_0)$ no dependa de $u$. Dado que $Z_0$ es $\mathcal{F}_0\text{-medible}$, entonces $\sigma(Z_0)$ también lo es, más aún, es $\mathcal{F}_u\text{-medible}$ para toda $u\geq 0$. Por lo tanto el termino a integrar del proceso $M(s)$, el cuál es una integral de Itô, es adaptado. Por hipotésis, de la condición (C2), podemos afirmar que

$$
        \mathbb{E}[|\sigma(Z_0)|^2] \leq K_2(1+\mathbb{E}[|Z_0|^2])\leq \infty.
$$

Esto pues obteniendo el valor esperado de (@eq-3) , tomando a $y=Z_0$ tenemos

$$
    \begin{aligned}
        \mathbb{E}[|\sigma(Z_0)|^2] & \leq \mathbb{E}\Bigg[|b(Z_0)|^2+|\sigma(Z_0)|^2+\int_{|x|<c} |F(Z_0,x)|^2 \nu(dx)\Bigg]\\ 
        & \leq \mathbb{E}[K_2(1+|Z_0|^2)]\\ 
        & = K_2\mathbb{E}[1+|Z_0|^2]\\ 
        & = K_2 (1+\mathbb{E}[|Z_0|^2]).
    \end{aligned}
$$ {#eq-6}

Por lo tanto, el proceso $M(s)$ es una martingala. Así, usando la desigualdad maximal de Doob, tenemos que:

$$
    \mathbb{E}\Bigg[\sup\limits_{0\leq s\leq t}|M(s)|^2\Bigg]\leq 4\mathbb{E}[|M(t)|^2].
$$

De la isometría de Itô y por el teorema de Fubini

$$
    \begin{aligned}
        \mathbb{E}\Bigg[\sup\limits_{0\leq s\leq t}|M(s)|^2\Bigg] & \leq 4\mathbb{E}[|M(t)|^2]\\ 
        & = 4 \mathbb{E}\Bigg[\int_0^t |\sigma(Z_0)|^2ds\Bigg]\\ 
        & = 4 \int_0^t \mathbb{E}[|\sigma(Z_0)|^2]ds\\ 
        & = 4 \mathbb{E}[|\sigma(Z_0)|^2]\int_0^t ds\\ 
        & = 4t \mathbb{E}[|\sigma(Z_0)|^2].
    \end{aligned}
$$

De manera análoga, para el termino

$$
    W(s):= \int_0^s\int_{|x|<c}F(Z_0,x)\widetilde{N}(du,dx).
$$

Podemos afirmar que es una martingala. Usando la isometría de Itô, desigualdad maximal de Doob y por el teorema de Fubini

$$
    \begin{aligned}
        \mathbb{E}\Bigg[\sup\limits_{0\leq s\leq t}|W(s)|^2\Bigg] & \leq 4\mathbb{E}[|W(t)|^2]\\ 
        & = 4\int_0^t\int_{|x|<c}\mathbb{E}[|F(Z_0,x)|^2]\nu(dx)ds\\ 
        & = 4t\int_{|x|<c}\mathbb{E}[|F(Z_0,x)|^2]\nu(dx).
    \end{aligned}
$$

Así, de la igualdad (@eq-5) tenemos

$$
    \begin{aligned}
        \mathbb{E}\Bigg[\sup\limits_{0\leq s\leq t}|Z_1(s)-Z_0|^2\Bigg] 
        & \leq 3\Bigg( \mathbb{E}\Bigg[\sup\limits_{0\leq s\leq t}\left(\int_0^s b(Z_0)\,ds\right)^2\Bigg]\\ 
            &\qquad
               + \mathbb{E}\Bigg[\sup\limits_{0\leq s\leq t} \left(\int_0^s \sigma(Z_0)\,dB(s)\right)^2\Bigg]\\
        &\qquad\quad
            +\mathbb{E}\Bigg[\sup\limits_{0\leq s\leq t} \left(\int_0^s\!\!\int_{|x|<c} F(Z_0,x)\,\widetilde{N}(ds,dx)\right)^2\Bigg]\Bigg)\\
        & \leq 3\Bigg(t^2\mathbb{E}[|b(Z_0)|^2]+4t\mathbb{E}[|\sigma(Z_0)|^2]\\ 
        & \qquad\quad + 4t\int_{|x|<c}\mathbb{E}[|F(Z_0,x)|^2]\nu(dx)\Bigg)\\ 
        & = 3t^2\mathbb{E}[|b(Z_0)|^2]+12t\mathbb{E}[|\sigma(Z_0)|^2]\\ 
        & \qquad\quad +12t\int_{|x|<c}\mathbb{E}[|F(Z_0,x)|^2]\nu(dx).
    \end{aligned}
$$ {#eq-7}

Notemos para los terminos en común $3t^2$ y $12t$ podemos definir la variable $C_1(t):=\max{\{3t,12\}}$, de aquí

$$
    \begin{aligned}
        3t^2 & = 3t\cdot t \leq \max{\{3t,12\}}\cdot t = C_1(t)\cdot t.\\ 
        12t & = 12\cdot t \leq \max{\{3t,12\}}\cdot t = C_1(t)\cdot t.
    \end{aligned}
$$

Por lo tanto, (@eq-7) queda de la forma

$$
    \begin{aligned}
        \mathbb{E}\Bigg[\sup\limits_{0\leq s\leq t}|Z_1(s)-Z_0|^2\Bigg] 
        & \leq 3t^2\mathbb{E}[|b(Z_0)|^2]+12t\mathbb{E}[|\sigma(Z_0)|^2]\\ 
        & \qquad\quad +12t\int_{|x|<c}\mathbb{E}[|F(Z_0,x)|^2]\nu(dx)\\ 
        & \leq C_1(t)\cdot t\Bigg(\mathbb{E}[|b(Z_0)|^2]+\mathbb{E}[|\sigma(Z_0)|^2]\\ 
        & \qquad \qquad\quad+\int_{|x|<c}\mathbb{E}[|F(Z_0,x)|^2]\nu(dx)\Bigg).
    \end{aligned}
$$ {#eq-8}

Por hipotésis, los coeficientes $b$, $\sigma$ y $F$ cumplen con la condición (@eq-3), vale decir

$$
    |b(Z_0)|^2+|\sigma(Z_0)|^2+\int_{|x|<c}|F(Z_0,x)|\nu(dx)\leq K_2(1+|Z_0|^2).
$$

De (@eq-6) podemos afirmar que $\mathbb{E}[K_2(1+|Z_0|^2)]=K_2(1+\mathbb{E}[|Z_0|^2])$, tomando valor esperado de la ecuación anterior, tenemos

$$
    \begin{aligned}
        \mathbb{E}\Bigg[|b(Z_0)|^2+|\sigma(Z_0)|^2+\int_{|x|<c}|F(Z_0,x)|\nu(dx)\Bigg] & \leq \mathbb{E}[K_2(1+|Z_0|^2)].\\
        \mathbb{E}[|b(Z_0)|^2]+\mathbb{E}[|Z_0|^2]+\mathbb{E}\Bigg[\int_{|x|<c}|F(Z_0,x)|^2\nu(dx)\Bigg] & \leq K_2(1+\mathbb{E}[|Z_0|^2]).\\ 
        \mathbb{E}[|b(Z_0)|^2]+\mathbb{E}[|Z_0|^2]+\int_{|x|<c}\mathbb{E}[|F(Z_0,x)|^2]\nu(dx)& \leq K_2(1+\mathbb{E}[|Z_0|^2]).    
    \end{aligned}
$$ {#eq-9}

Así de (@eq-8) y (@eq-9) tenemos que

$$
    \begin{aligned}
        \mathbb{E}\Bigg[\sup\limits_{0\leq s\leq t}|Z_1(s)-Z_0|^2\Bigg]
        & \leq C_1(t)\Bigg(\mathbb{E}[|b(Z_0)|^2]+\mathbb{E}[|\sigma(Z_0)|^2]\\ 
        & \qquad \qquad\quad+\int_{|x|<c}\mathbb{E}[|F(Z_0,x)|^2]\nu(dx)\Bigg)\\
        & \leq C_1(t)\cdot t\cdot K_2(1+\mathbb{E}[|Z_0|^2]).
    \end{aligned}
$$

Peamos la diferencia para $Z_{n+1}$ y $Z_n$, por la iteración de Picard, tenemos que

$$
    \begin{aligned}
        Z_n & = Z_0 + \int_0^t b(Z_{n-1}(s-))ds+\int_0^t \sigma(Z_{n-1}(s-))dB(s)\\ 
        &\qquad\quad + \int_0^t \int_{|x|<c} F(Z_{n-1}(s-),x)\widetilde{N}(ds,dx)\\ 
        Z_{n+1} & = Z_0 + \int_0^t b(Z_{n}(s-))ds+\int_0^t \sigma(Z_{n}(s-))dB(s)\\ 
        &\qquad\quad + \int_0^t \int_{|x|<c} F(Z_{n}(s-),x)\widetilde{N}(ds,dx).
    \end{aligned}
$$

Consideremos la siguiente notación

$$
    \begin{aligned}
        \Delta b(n,s) & = b(Z_n(s-))-b(Z_{n-1}(s-)).\\ 
        \Delta \sigma(n,s) & = \sigma(Z_n(s-))-\sigma(Z_{n-1}(s-)).\\ 
        \Delta F(n,s,x) & = F(Z_n(s-),x)-F(Z_{n-1}(s-),x).
    \end{aligned}
$$

Por lo tanto la diferencia $Z_{n+1}-Z_n$ está dada por

$$
    \begin{aligned}
        Z_{n+1}(t)-Z_n(t) & = \int_0^t \Delta b(n,s)ds + \int_0^t \Delta \sigma(n,s)dB(s)\\ 
        & \qquad \quad +\int_0^t\int_{|x|<c}\Delta F(n,s,x)\widetilde{N}(ds,dx).
    \end{aligned}
$$

Elevando al cuadrado, considerando valor absoluto y usando la desigualdad (@eq-des), tenemos que

$$
    \begin{aligned}
        |Z_{n+1}(t)-Z_n(t)|^2 & = \Bigg( \int_0^t \Delta b(n,s)ds + \int_0^t \Delta \sigma(n,s)dB(s)\\ 
        &\qquad\quad +\int_0^t\int_{|x|<c}\Delta F(n,s,x)\widetilde{N}(ds,dx)\Bigg)^2\\ 
        & \leq 3\Bigg(\Bigg(\int_0^t \Delta b(n,s)ds\Bigg)^2+\Bigg(\int_0^t  \Delta \sigma(n,s)ds\Bigg)^2\\ 
        &\qquad\quad +\Bigg(\int_0^t\int_{|x|<c}\Delta F(n,s,c)\widetilde{N}(ds,dx)\Bigg)^2\Bigg).
    \end{aligned}
$$ {#eq-10}

Nuevamente, definimos la siguiente notación

$$
    \begin{aligned}
        A & := \mathbb{E}\Bigg[\sup\limits_{0\leq s\leq t}\Bigg(\int_0^s \Delta b(n,u)du\Bigg)^2\Bigg]\\ 
        B & := \mathbb{E}\Bigg[\sup\limits_{0\leq s\leq t}\Bigg(\int_0^s \Delta \sigma(n,u)dB(u)\Bigg)^2\Bigg]\\ 
        C & := \mathbb{E}\Bigg[\sup\limits_{0\leq s\leq t}\Bigg(\int_0^s \Delta F(n,u,x)\widetilde{N}(du,dx)\Bigg)^2\Bigg]
    \end{aligned}
$$

Por tanto de la (@eq-10), tomando supremo en el intervalo $[0,t]$ y aplicando valor esperado, la expresión se reduce a la forma

$$
    \mathbb{E}\Bigg[\sup\limits_{0\leq s\leq t} |Z_{n+1}(s)-Z_n(s)|^2\Bigg]\leq 3(A+B+C).
$$ {#eq-11}

Trabajaremos con cada termino de la desigualdad para poder acotar $\displaystyle \mathbb{E}\Bigg[\sup\limits_{0\leq s\leq t} |Z_{n+1}(t)-Z_n(t)|^2\Bigg]$. Notemos que para $A$ el termino del supremo es una integral de Lebesgue, por lo que usando la Desigualdad de Cauchy-Schwarz podemos afirmar que

$$  
    \Bigg(\int_0^s \Delta b(n,u)du\Bigg)^2\leq s \int_0^s |\Delta b(n,u)|^2du,\ \ \forall s\in [0,t].
$$

Dado que $s\leq t$, esto implica que

$$
    s \int_0^s |\Delta b(n,u)|^2du\leq t\int_0^t |\Delta b(n,u)|^2du.
$$

Dado que el supremo preserva desigualdades, tenemos

$$
    \begin{aligned}
            \sup\limits_{0\leq s\leq t} \Bigg(\int_0^s \Delta b(n,u)du\Bigg)^2 & \leq \sup\limits_{0\leq s\leq t}\Bigg(s \int_0^s |\Delta b(n,u)|^2du\Bigg)\\ 
            & \leq \sup\limits_{0\leq s\leq t}\Bigg(t\int_0^t |\Delta b(n,u)|^2du\Bigg)\\ 
            & = t\int_0^t |\Delta b(n,u)|^2du.
    \end{aligned}
$$

Tomando el valor esperado

$$
    \begin{aligned}
        A & = \mathbb{E}\Bigg[\sup\limits_{0\leq s\leq t}\Bigg(\int_0^s \Delta b(n,u)du\Bigg)^2\Bigg]\\ 
        & \leq \mathbb{E}\Bigg[t\int_0^t |\Delta b(n,u)|^2du\Bigg]\\ 
        & = t\int_0^t \mathbb{E}[|\Delta b(n,u)|^2]du.
    \end{aligned}
$$

Definimos al proceso $H(s)$ de la forma

$$
    H(s) := \int_0^s \Delta \sigma(n,u)dB(u).
$$

Afirmamos que dicho proceso es una martingala bajo los argumentos para el proceso $M(s)$ en (@eq-mart). Haciendo uso de la desigualdad maximal de Doob

$$
    \mathbb{E}\Bigg[\sup\limits_{0\leq s\leq t}|H(s)|^2\Bigg]\leq 4\mathbb{E}[|H(t)|^2].
$$

Usando la isometría de Itô

$$
    \mathbb{E}[|H(s)|^2]=\mathbb{E}\Bigg[\int_0^t |\Delta \sigma(n,u)|^2 du\Bigg].
$$

Esto implica que

$$
    \begin{aligned}
        B & = \mathbb{E}\Bigg[\sup\limits_{0\leq s\leq t}\left(|H(s)|^2\right)\Bigg]\\ 
        & \leq 4\mathbb{E}[|H(t)|^2]\\ 
        & = 4 \mathbb{E}\Bigg[\int_0^t |\Delta \sigma(n,u)|^2du\Bigg]\\ 
        & = 4 \int_0^t \mathbb{E}[|\Delta \sigma(n,u)|^2]du.
    \end{aligned}
$$

Definimos el proceso

$$
    L(s) := \int_0^s\int_{|x|<c} \Delta F(n,u,x)\widetilde{N}(du,dx).
$$

Afirmamos que dicho proceso es una martingala. Aplicando la desigualdad de Doob, obtenemos

$$
    \mathbb{E}\Bigg[\sup\limits_{0\leq s\leq t} |L(s)|^2\Bigg]\leq 4\mathbb{E}\left[|L(t)|^2\right].
$$

Por la isometría de Itô en la medida de Poisson, tenemos

$$
    \begin{aligned}
        \mathbb{E}\left[|L(t)|^2\right] & = \mathbb{E}\Bigg[\int_0^t\Bigg(\int_{|x|<c}|\Delta F(n,u,x)|^2\nu(dx)\Bigg)du\Bigg]\\ 
        & = \int_0^t\int_{|x|<c}\mathbb{E}\left[|\Delta F(n,u,x)|^2\right]\nu(dx)du.
    \end{aligned}
$$

Por lo tanto

$$
    \begin{aligned}
        C & = \mathbb{E}\Bigg[\sup\limits_{0\leq s\leq t}\left|\int_0^s\int_{|x|<c}\Delta F(n,u,x)\widetilde{N}(du,dx)\right|^2\Bigg]\\ 
        & \leq 4 \int_0^t\int_{|x|<c}\mathbb{E}\left[|\Delta F(n,u,x)|^2\right]\nu(dx)du.
    \end{aligned}
$$

Así de (@eq-11)

$$
    \begin{aligned}
        \mathbb{E}\left[\sup\limits_{0\leq s\leq t} \left|Z_{n+1}(s-)-Z_n(s-)\right|^2\right] & \leq 3(A+B+C)\\ 
        & \leq 3\Bigg(t\int_0^t \mathbb{E}\left[|\Delta b(n,u)|^2\right]du\\ 
        & \qquad + 4\int_0^t \mathbb{E}\left[|\Delta \sigma(n,u)|^2\right]du\Bigg)\\ 
        &  \qquad\quad + 4\int_0^t\int_{|x|<c}\mathbb{E}\left[|\Delta F(n,u,x)|^2\right]\nu(dx)du\\ 
        & = 3t\int_0^t \mathbb{E}\left[|\Delta b(n,u)|^2\right]du\\ 
        & \qquad + 12\int_0^t \mathbb{E}\left[|\Delta \sigma(n,u)|^2\right]du\\ 
        &  \qquad\quad + 12\int_0^t\int_{|x|<c}\mathbb{E}\left[|\Delta F(n,u,x)|^2\right]\nu(dx)du.
    \end{aligned}
$$

Recordemos que $C_1(t)=\max\{3t,12\}$, por lo tanto, $3t\leq C_1(t)$ y $12\leq C_1(t)$, así

$$
    \begin{aligned}
        \mathbb{E}\left[\sup\limits_{0\leq s\leq t} \left|Z_{n+1}(s-)-Z_n(s-)\right|^2\right] & \leq 3t\int_0^t \mathbb{E}\left[|\Delta b(n,u)|^2\right]du\\ 
        & \qquad + 12\int_0^t \mathbb{E}\left[|\Delta \sigma(n,u)|^2\right]du\\ 
        &  \qquad\quad + 12\int_0^t\int_{|x|<c}\mathbb{E}\left[|\Delta F(n,u,x)|^2\right]\nu(dx)du\\
        & \leq C_1(t)\int_0^t \mathbb{E}\left[|\Delta b(n,u)|^2\right]du\\ 
        & \qquad + C_1(t)\int_0^t \mathbb{E}\left[|\Delta \sigma(n,u)|^2\right]du\\ 
        &  \qquad\quad + C_1(t)\int_0^t\int_{|x|<c}\mathbb{E}\left[|\Delta F(n,u,x)|^2\right]\nu(dx)du\\
        & = C_1(t)\int_0^t\Bigg(\mathbb{E}\left[|\Delta b(n,u)|^2\right]+\mathbb{E}\left[|\Delta \sigma(n,u)|^2\right]\\ 
        & \qquad + \int_{|x|<c}\mathbb{E}\left[|\Delta F(n,u,x)|^2\right]\nu(dx)\Bigg)du.
    \end{aligned}
$$

Recordemos que si $f:[0,t]$ es una función, entonces para todo $v\in [0,t]$ se cumple que

$$
    |f(v)|\leq \sup\limits_{0\leq u\leq t}|f(u)|.
$$

Así, tenemos que

$$
    |Z_n(u-)-Z_{n-1}(u-)|^2\leq \sup\limits_{0\leq v\leq u}|Z_n(v)-Z_{n-1}(v)|^2.
$$

Tomando valor esperado, el cual, preserva la desigualdad, además, multiplicando por $K_1>0$, obtenemos

$$
    K_1\mathbb{E}\left[|Z_n(u-)-Z_{n-1}(u-)|^2\right] \leq K_1\mathbb{E}\left[\sup\limits_{0\leq v\leq u}|Z_n(v)-Z_{n-1}(v)|^2\right].
$$ {#eq-12}

Por la hipotesis (@eq-lipschitz) la cuál indica que los coeficientes $b$, $\sigma$ y $F$ satisfacen

$$
    \begin{aligned}
    |b(y_1) - b(y_2)|^2 & + |\sigma(y_1) - \sigma(y_2)|^2\\ 
    & + \int_{|x| < c} |F(y_1, x) - F(y_2, x)|^2 \, \nu(dx) \\
    &\qquad \quad \leq K_1 |y_1 - y_2|^2.
    \end{aligned}
$$

Aplicando esto para $y_1=Z_n(u-)$ y $y_2=Z_{n-1}(u-)$, además tomando valor esperado, tenemos

$$
    \begin{aligned}
        \mathbb{E}\left[|b(Z_n(u-))-b(Z_{n-1}(u-))|^2\right] & + \mathbb{E}\left[|\sigma(Z_n(u-))-\sigma(Z_{n-1}(u-))|^2\right]\\ 
        & \quad + \mathbb{E}\left[\int_{|x<c|}|F(Z_n(u-),x)-F(Z_{n-1}(u-),x)|^2\nu(dx)\right]\\ 
        & \qquad\quad \leq K_1 \mathbb{E}\left[|Z_n(u-)-Z_{n-1}(u-)|^2\right]\\ 
        & \qquad\quad \leq K_1\mathbb{E}\left[\sup\limits_{0\leq v\leq u}|Z_n(v)-Z_{n-1}(v)|^2\right].
    \end{aligned}
$$

Multiplicando por la variable $C_1(t)$ e intregrando en el intervalo $[0,t]$ con respecto a $u$ tenemos que

$$
    \begin{aligned}
        \mathbb{E}\left[\sup\limits_{0\leq s\leq t}|Z_{n+1}(s)-Z_n(s)|^2\right] & = C_1(t)\int_0^t \Bigg(\mathbb{E}\left[|b(Z_n(u-))-b(Z_{n-1}(u-))|^2\right]\\ 
        & \qquad\qquad\quad + \mathbb{E}\left[|\sigma(Z_n(u-))-\sigma(Z_{n-1}(u-))|^2\right]\\ 
        & \qquad\qquad\quad + \mathbb{E}\left[\int_{|x|<c}|F(Z_n(u-),x)-F(Z_{n-1}(u-),x)|^2\nu(dx)\right]\Bigg)du\\ 
        & \leq C_1(t) K_1\int_0^t \mathbb{E}\left[\sup\limits_{0\leq v\leq u}|Z_n(u)-Z_{n-1}(u)|^2\right]du.
    \end{aligned}
$$

Ahora bien, para $n\geq 1$ y $t\geq 0$ definimos el siguiente proceso

$$
    d_n(t):= \mathbb{E}\left[\sup\limits_{0\leq s\leq t}|Z_n(s)-Z_{n-1}(s)|^2\right].
$$

Hemos demostrado hasta ahora las siguientes desigualdades

$$
    d_1(t) = \mathbb{E}\left[\sup\limits_{0\leq s\leq t}|Z_1(s)-Z_0|^2\right]\leq C_1(t)K_2(1+\mathbb{E}[|Z_0|^2]).
$$ {#eq-13}

$$
    d_{n+1}(t) = \mathbb{E}\left[\sup\limits_{0\leq s\leq t}|Z_{n+1}(s)-Z_n(s)|^2\right]\leq C_1(t)K_1\int_0^t d_n(s)ds.
$$ {#eq-14}

Definimos las variables $C_2(t):=tC_1(t)$ y $K_3:=\max\{K_1,K_2(1+\mathbb{E}[|Z_0|^2])\}$.\\

Afirmamos que para toda $n\in \mathbb{N}$, se cumple

$$
    d_n(t)\leq \frac{C_2(t)^n K_3^n}{n!}.
$$ {#eq-15}

Procediendo por inducción, veamos que se cumple para $n=1$. Esto es claro, dado que $K_2(1+\mathbb{E}[|Z_0|^2])\leq \max\{K_1,K_2(1+\mathbb{E}[|Z_0|^2])\}=K_3$, por lo tanto

$$
    d_1(t)\leq C_1(t)tK_2(1+\mathbb{E}[|Z_0|^2])\leq C_2(t)K_3 = \frac{C_2(t)^1 K_3^1}{1!}.
$$

Suponemos ahora la afirmación es cierta para $n=k$, es decir

$$
    d_k(t)\leq \frac{C_2(t)^k K_3^k}{k!}.
$$

Veamos ahora que se cumple para $n=k+1$, vale decir, queremos probar que

$$
    d_{k+1}(t)\leq \frac{C_2(t)^{k+1} K_3^{k+1}}{(k+1)!}.
$$

Por la (@eq-14) tenemos

$$
        d_{k+1} \leq C_1(t)K_1\int_0^t d_k(s)ds.
$$

Usando la Hipotesis de inducción, podemos afirmar que

$$
    d_{k+1}(t) \leq C_1(t)K_1\int_0^t d_k(s)ds\leq C_1(t)K_1\int_0^t \frac{C_2(t)^kK_3^k}{k!}.
$$

Aquí debemos considerar los siguientes casos

**Caso 1:** $t<1$

Dado que $0\leq s\leq t<1$, entonces $3s\leq 3t<3<12$, por lo tanto

$$
    C_1(s)=\max\{3s,12\}=12=\max\{3t,12\}=C_1(t).
$$

**Caso 2:** $t\geq 1$

Es claro que si $s\leq t$, entonces $3s\leq 3t$, por tanto, podemos afimar

$$
    C_1(s)=\max\{3s,12\}\leq \max\{3t,12\}=C_1(t).
$$

En ambos casos note que se cumple $C_1(s)\leq C_1(t)$, más aún es claro que $K_1\leq K_3$, esto implica que $K_1K_3^k\leq K_3^{k+1}$ por lo tanto

$$
    \begin{aligned}
        d_{k+1}(t) & \leq C_1(t)K_1\int_0^t d_k(s)ds\\ 
        & \leq C_1(t)K_1\int_0^t \frac{C_2(t)^k K_3^k}{k!}ds.\\ 
        & = \frac{C_1(t)K_1 K_3^k}{k!}\int_0^t s^kC_1(s)^k ds\\ 
        & \leq \frac{C_1(t)K_3^{k+1}}{k!}\int_0^t s^k C_1(s)^k ds\\
        & \leq \frac{C_1(t)K_3^{k+1}}{k!}\int_0^t s^k C_1(t)^k ds\\ 
        & = \frac{C_1(t)C_1(t)^k K_3^{k+1}}{k!}\int_0^t s^k ds\\ 
        & = \frac{C_1(t)^{k+1}K_3^{k+1}}{k!}\frac{t^{k+1}}{k+1}\\ 
        & = \frac{t^{k+1}C_1(t)^{k+1}K_3^{k+1}}{(k+1)!}\\ 
        & = \frac{C_2(t)^{k+1}K_3^{k+1}}{(k+1)!}.
    \end{aligned}
$$

Por lo tanto para toda $n\in \mathbb{N}$ se cumple

$$
d_{n}(t)\leq \frac{C_2^k K_3^n}{n!}.
$$

Veamos que la sucesión $\{Z_n(t)\}_{n\in \mathbb{N}}$ es una sucesión de Cauchy en $L^2$ usando la norma $\|\cdot\|_2:=[\mathbb{E}(|\cdot|^2)]^{1/2}$ el cuál hace de $L^2$ un espacio completo.

Sean $m,n\mathbb{N}$, sin perdida de generalidad, supongamos que $m<n$, aplicando la desigualdad del triangulo, podemos afirmmar que para cada $0\leq s\leq t$ se cumple

$$
    \begin{aligned}
        \|Z_n(s)-Z_m(s)\|_2 & = \Bigg\|\sum\limits_{r=m+1}^n (Z_r(s)-Z_{r-1}(s))\Bigg\|_2\\ 
        & \leq \sum\limits_{r=m+1}^n\|Z_r(s)-Z_{r-1}(s)\|_2.
    \end{aligned}
$$

De la (@eq-15) sabemos que para cada $r=m+1,m+2,\ldots,n$ se cumple

$$
    \mathbb{E}\Bigg[\sup\limits_{0\leq s\leq t}|Z_r(s)-Z_{r-1}(s)|^2\Bigg]\leq \frac{C_2(t)^rK_3^r}{r!}.
$$

Dado que son terminos no negativos, tomando raíz se puede afirmar que

$$
    \begin{aligned}
        \|Z_r(s)-Z_{r-1}(s)\|_2 & \leq \sqrt{\mathbb{E}\Bigg[\sup\limits_{0\leq u\leq t}|Z_r(s)-Z_{r-1}(s)|^2\Bigg]}\\ 
        & \leq \frac{C_2(t)^{r/2}K_3^{r/2}}{(r!)^{r/2}}.
    \end{aligned}
$$

Por tanto para cada $0\leq s\leq t$ tenemos

$$
    \begin{aligned}
        \|Z_n(s)-Z_m(s)\|_2 & \leq \sum\limits_{r=m+1}^n \|Z_r(s)-Z_{r-1}(s)\|_2\\ 
        & \leq \sum\limits_{r=m+1}^n \frac{C_2(t)^{r/2}K_3^{r/2}}{(r!)^{r/2}}.
    \end{aligned}
$$

Definimos la siguiente variable

$$
    A':=C_2(t)K_3>0.
$$

Reescribiendo el termino de la suma de la siguiente forma

$$
    a_r=\frac{A^{r/2}}{(r!)^{1/2}}=\Bigg(\frac{A^r}{r!}\Bigg)^{1/2}.
$$ {#eq-16}

Veamos la convergencía de la serie

$$
\sum\limits_{r=1}^{\infty} a_r=\sum\limits_{r=1}^{\infty} \Bigg(\frac{A^r}{r!}\Bigg)^{1/2}.
$$

Considerando el cociente del termino $a_r$ tenemos

$$
    \begin{aligned}
        \frac{a_{r+1}}{a_r} & = \frac{\Bigg(\frac{A^{r+1}}{(r+1)!}\Bigg)^{1/2}}{\Bigg(\frac{A^r}{r!}\Bigg)^{1/2}}\\ 
        & = \Bigg(\frac{A^{r+1}}{(r+1)!}\cdot \frac{r!}{A^r}\Bigg)^{1/2}\\ 
        & = \Bigg(\frac{A}{r+1}\Bigg)^{1/2}.
    \end{aligned}
$$

Ahora tomando el límite cuando $r\rightarrow\infty$

$$
\lim\limits_{r\rightarrow\infty}\frac{a_{r+1}}{a_r}=\lim\limits_{r\rightarrow\infty}\sqrt{\frac{A}{r+1}}=0.
$$

Dado que este límite es estrictamente menor que 1, por el criterio de la razón, podemos afirmar que la serie converge absolutamente esto implica que la serie converge, más aún, su cola converge, es decir, para todo $\varepsilon>0$ existe $N\in \mathbb{N}$ tal que

$$
    \sum\limits_{r=N+1}^{\infty}\frac{C_2(t)^{r/2}K_3^{r/2}}{(r!)^r/2}<\varepsilon.
$$

Entonces, para todo $n,m\geq N$ tales que $m<n$ y todo $s\in [0,t]$

$$
    \|Z_n(s)-Z_m(s)\|_2\leq \sum\limits_{r=m+1}^n\frac{C_2(t)^{r/2}K_3^{r/2}}{(r!)^{r/2}}\leq \sum\limits_{r=N+1}^{\infty} \frac{C_2(t)^{r/2}K_3^{r/2}}{(r!)^{r/2}}<\varepsilon.
$$

Por lo tanto, podemos afirmar que $(Z_n(s))$ es una sucesión de Cauchy en $L^2$.

Al ser $L^2(\Omega, \mathcal{F},\mathbb{P})$ un espacio de Banach, vale decir, es un espacio completo con la norma $\|\cdot\|_2$, entonces toda sucesión de Cauchy converge en $L^2$. Luego existe $Z(s)\in L^2$ tal que

$$
    \lim\limits_{m\rightarrow \infty}\|Z_m(s)-Z(s)\|_2=0, \ \ \ \forall s\in [0,t].
$$ {#eq-17}

Cómo $m<n$, por la desigualdad del triángulo, afirmamos que

$$
    \|Z(s)-Z_n(s)\|_2\leq \|Z(s)-Z_m(s)\|_2+\|Z_m(s)-Z_n(s)\|_2.
$$

Tomando límite cuando $m\rightarrow\infty$ en ambos lados; por la @eq-17 tenemos que

$$
    \lim\limits_{m\rightarrow \infty}\|Z_m(s)-Z(s)\|_2=0.
$$

Luego, dado que ya se demostró que la seríe dada por @eq-16 converge entonces

$$
    \lim\limits_{m\rightarrow\infty} \|Z_m(s)-Z_n(s)\|_2\leq \lim\limits_{m\rightarrow\infty}\sum\limits_{r=n+1}^m\frac{C_2(t)^{r/2}K_3^{r/2}}{(r!)^{r/2}}=\sum\limits_{r=n+1}^{\infty}\frac{C_2(t)^{r/2}K_3^{r/2}}{(r!)^{r/2}}.
$$

Además el termino $\|Z(s)-Z_n(s)\|_2$ no depende de $m$, por lo tanto

$$
    \|Z(s)-Z_n(s)\|_2\leq \sum\limits_{r=n+1}^{\infty}\frac{C_2(t)^{r/2}K_3^{r/2}}{(r!)^{r/2}}.
$$

Consideremos ahora la siguiente notación

$$
    X_n:=\sup\limits_{0\leq s\leq t} |Z_n(s)-Z_{n-1}(s)|. 
$$

Queremos encontrar una cota para

$$
    \mathbb{P}\Bigg(X_n\geq\frac{1}{2^n}\Bigg).
$$

Aplicando a $X_n^2$ Chebyshev-Markov tenemos que

$$
    \mathbb{P}\Bigg(X_n\geq\frac{1}{2^n}\Bigg)=\mathbb{P}\Bigg(X_n^2\geq \frac{1}{4^n}\Bigg)\leq 4^n\mathbb{E}[X_n^2].
$$ {#eq-18}

Notemos que $\mathbb{E}[X_n^2]$ ya esta acotado dado por la @eq-15, así

$$
    \mathbb{E}[X_n^2]=\mathbb{E}\Bigg[\sup\limits_{0\leq s\leq t}|Z_n(s)-Z_{n-1}(s)|^2\Bigg]\leq \frac{C_2(t)^nK_3^n}{n!}.
$$

De la @eq-18, esto implica que

$$
    \mathbb{P}\Bigg(X_n\geq\frac{1}{2^n}\Bigg)\leq 4^n\frac{C_2(t)^2K_3^n}{n!}=\frac{(4C_2(t)K_3)^n}{n!}.
$$

Más aún, sabemos que la seríe $\displaystyle \frac{C_2(t)^nK_3^n}{n!}$, esto implica que $\displaystyle \frac{(4C_2(t)K_3)^n}{n!}$ también coverge, por lo tanto

$$
    \sum\limits_{n=1}^{\infty} \mathbb{P}\Bigg(\sup\limits_{0\leq s\leq t}|Z_n(s)-Z_{n-1}(s)|\geq \frac{1}{2^n}\Bigg)\leq \sum\limits_{n=1}^{\infty} \frac{(4C_2(t)K_3)^n}{n!}<\infty.
$$

De aquí es posible usar el Lema de Borell-Cantelli, es decir, podemos afirmar

$$
    \mathbb{P}\Bigg(\limsup\limits_{n\rightarrow \infty}\Bigg\{\sup\limits_{0\leq s\leq t}|Z_n(s)-Z_{n-1}(s)|\geq \frac{1}{2^n}\Bigg\}\Bigg)=0.
$$

La estimación obtenida nos dice que la probabilidad de que las diferencias consecutivas $|Z_n(s) - Z_{n-1}(s)|$ sean "grandes" (mayores que $1/2^n$) se vuelve extremadamente pequeña a medida que $n$ crece, tan pequeña que la suma de todas esas probabilidades es finita.

En otras palabras, casi todas las trayectorias de la sucesión $(Z_n)$ se vuelven uniformemente estables, a partir de algún momento, los términos de la sucesión ya no cambian mucho entre sí, ni en ningún instante del intervalo $[0,t]$.

Esto garantiza que, con probabilidad 1, la sucesión $(Z_n(\cdot))$ converge uniformemente en $[0,t]$ a una función límite $Z(\cdot)$. Es decir, no solo converge punto a punto, sino que lo hace de manera controlada en todo el intervalo al mismo tiempo.

Veamos ahora que dicha solución es única, así supongamos que $Z^{(1)}= (Z^{(1)}(t))_{t \geq 0}$ y $Z^{(2)} = (Z^{(2)}(t))_{t \geq 0}$ son dos soluciones fuertes de la SDE modificada, es decir, procesos adaptados, càdlàg, cuadrado-integrables y que satisfacen, para todo $t \geq 0$, las ecuaciones integrales:

$$
    \begin{aligned}
        Z^{(i)}(t) & = Z_0 + \int_0^t b(Z^{(i)}(s-))\,ds\\ 
        & \qquad \quad + \int_0^t \sigma(Z^{(i)}(s-))\,dB(s)\\ 
        & \qquad\quad + \int_0^t \int_{|x|<c} F(Z^{(i)}(s-), x)\,\tilde{N}(ds,dx),
    \end{aligned}
$$

para $i=1,2$, casi seguramente. Queremos ver que $Z^{(1)}(t) = Z^{(2)}(t)$ para todo $t\geq 0$ con probabilidad $1$. Restando las dos ecuaciones de $Z^{(1)}$ y $Z^{(2)}$ tenemos que

$$
    \begin{aligned}
        Z^{(1)}(t) - Z^{(2)}(t) & = \int_0^t [b(Z^{(1)}(s-)) - b(Z^{(2)}(s-))]\,ds\\ 
        & \qquad + \int_0^t [\sigma(Z^{(1)}(s-)) - \sigma(Z^{(2)}(s-))]\,dB(s)\\ 
        & \qquad\quad + \int_0^t \int_{|x|<c} [F(Z^{(1)}(s-), x) - F(Z^{(2)}(s-), x)]\,\tilde{N}(ds,dx). 
    \end{aligned}
$$ {#eq-19}

Definimos la siguiente notación

$$
    \begin{aligned}
        \Delta b(s) & :=b(Z^{(1)}(s-))-b(Z^{(2)}(s-))\\ 
        \Delta \sigma(s) & := \sigma(Z^{(1)}(s-))-\sigma(Z^{(2)}(s-))\\ 
        \Delta F(s,x) & := F(Z^{(1)}(s-),x)-F(Z^{(2)}(s-),x)
    \end{aligned}
$$

Nuestro objetivo ahora es estimar $\displaystyle \mathbb{E}\left[\sup\limits_{0\leq s\leq t}|Z^{(1)}(t) - Z^{(2)}(t)|^2\right]$. Para ello, similar al procedimiento anterior, elevando al cuadrado la @eq-19, tomando supremo y despues esperanza en el intervalo \$\[0,t\]\$\$ tenemos la siguiente desigualdad

$$
    \begin{aligned}
        \mathbb{E}\left[\sup\limits_{0\leq s\leq t}|Z^{(1)}(s) - Z^{(2)}(s)|^2\right] \leq & 3\Bigg(\mathbb{E}\left[\sup\limits_{0\leq s\leq t}\Bigg|\int_0^s [\Delta b(s)]du\Bigg|^2\right]\\ 
        &\quad + \mathbb{E}\left[\sup\limits_{0\leq s\leq t}\Bigg|\int_0^s [\sigma(s)]dB(u)\Bigg|^2\right]\\ 
        & \qquad + \mathbb{E}\left[\sup\limits_{0\leq s\leq t}\Bigg|\int_0^s\int_{|x|<c} [\Delta F(u,x)]\widetilde{N}(du,dx)\Bigg|^2\right]\Bigg).
    \end{aligned}
$$

Aplicando la desigualdad de Cauchy–Schwarz para integrales, para el primer termino de la desigualdad tenemos

$$
    \begin{aligned}
        \Bigg|\int_0^s \Delta b(u)du\Bigg|^2 & \leq s\int_0^s |\Delta b(u)|^2du\\ 
        & \leq t\int_0^t |\Delta b(u)|^2du.
    \end{aligned}
$$

Dado que $s\leq t$ al tomar supremo y valor esperado obtenemos la cota

$$
\mathbb{E}\left[\sup\limits_{o\leq s\leq t}\Bigg|\int_0^s \Delta b(u)du\Bigg|^2\right]\leq t\int_0^t \mathbb{E}[|\Delta b(u)|^2]du.
$$

Bajo argumentos similares utilizados anteriormente, afirmamos que el proceso

$$
    \int_0^s \Delta \sigma (u)\ dB(u), 
$$

es una martingala local continua, por tanto, usando la desigualdad maximal de Doob tenemos

$$
    \mathbb{E}\left[\sup\limits_{0\leq s\leq t}\left|\int_0^s \Delta \sigma (u)dB(u)\right|^2\right]\leq 4\mathbb{E}\left[\Bigg|\int_0^t \Delta \sigma (s)\ dB(s)\Bigg|^2\right].
$$

De aquí, usando la isometría de Itô

$$
\mathbb{E}\left[\Bigg|\int_0^t \Delta \sigma (s) dB(s)\Bigg|^2\right] \leq \mathbb{E}\Bigg[\int_0^t |\Delta \sigma (s)|^2ds\Bigg].
$$

Esto implica que

$$
    \mathbb{E}\Bigg[\int_0^t |\Delta \sigma (s)|^2ds\Bigg] = \int_0^t \mathbb{E}[|\Delta \sigma (s)|^2ds].
$$

Por lo tanto

$$
    \mathbb{E}\left[\sup\limits_{0\leq s\leq t}\left|\int_0^s \Delta \sigma (u)\ dB(u)\right|^2\right]\leq 4\int_0^t \mathbb{E}[|\Delta \sigma (s)|^2ds].
$$

Podemos afirmar ahora que el siguiente proceso es una martingala local càdlàg

$$
    \int_0^s\int_{|x|<c} \Delta F(u,x)\widetilde{N}(du,dx).
$$

Nuevamente aplicando la desigualdad maximal de Doob la isometría de Itô para integrales respecto a $\widetilde{N}$ tenemos que

$$
    \mathbb{E}\left[\sup\limits_{0\leq s\leq t}\left|\int_0^s\int_{|x|<c} \Delta F(u,x)\widetilde{N}(du,dx)\right|^2\right]\leq 4\int_0^t\int_{|x|<c}\mathbb{E}[|\Delta F(s,x)|^2]\nu(dx)ds.
$$

Por lo tanto

$$
    \begin{aligned}
        \mathbb{E}\left[\sup\limits_{0\leq s\leq t}\left|Z^{(1)}(s) - Z^{(2)}(s)\right|^2\right]\leq & 3t\int_0^t \mathbb{E}[|\Delta b(s)|^2]ds\\ 
        & \quad + 12 \int_0^t \mathbb{E}[|\Delta \sigma(s,x)|^2ds]\\ 
        & \qquad +12 \int_0^t\int_{|x|<c}\mathbb{E}[|\Delta F(s,x)|^2]\nu(dx)ds.
    \end{aligned}
$$

Usando y factorizando la variable ya defidina $C_1(t)$ tenemos que

$$
    \begin{aligned}
        \mathbb{E}\left[\sup\limits_{0\leq s\leq t}\left|Z^{(1)}(s) - Z^{(2)}(s)\right|^2\right]\leq & C_1(t)\int_0^t\Bigg(\mathbb{E}[|\Delta b(s)|^2]+\mathbb{E}[|\Delta \sigma(s)|^2]\\
        & \qquad\qquad +\int_{|x|<c}\mathbb{E}[|\Delta F(s,x)|^2]\nu(dx)\Bigg)ds.
    \end{aligned}
$$

De manera similar como ya se hizo en el análisis de la diferencia entre $Z_n$ y $Z_{n-1}$ en la iteración de Picard, haciendo uso de la condición (@eq-lipschitz) podemos obtener

$$
    \mathbb{E}\left[\sup\limits_{0\leq s\leq t}\left|Z^{(1)}(s) - Z^{(2)}(s)\right|^2\right]\leq C_1(t)K_1\int_0^t\mathbb{E}\left[\sup\limits_{0\leq u\leq s}|Z^{(1)}(u) - Z^{(2)}(u)|^2\right]ds.
$$

De esta forma definimos ahora la función

$$
    D(t):=\mathbb{E}\left[\sup\limits_{0\leq s\leq t}\left|Z^{(1)}(s) - Z^{(2)}(s)\right|^2\right].
$$

Es claro que $D(t)\geq 0$ para toda $t\geq 0$. Fijando a $T\geq 0$, podemos afirmar que para todo $t\in [0,T]$ la variable $C_1(t)\leq C_1(T)<\infty$. Por el Teorema de Gronwall tenemos que

$$
    D(t) \leq 0\cdot e^{C_1(T)K_1}=0, \qquad t\in [0,T].
$$

Por la arbitrariedad de $T$, tenemos que para todo $t\geq 0$ se cumple

$$
    D(t)=\mathbb{E}\left[\sup\limits_{0\leq s\leq t}\left|Z^{(1)}(s) - Z^{(2)}(s)\right|^2\right]=0.
$$

Por lo tanto, por propiedad de la esperanza podemos afirmar que

$$
\sup\limits_{0\leq s\leq t}\left|Z^{(1)}(s) - Z^{(2)}(s)\right|^2=0\ \ \text{c.s.}
$$

Es decir, $Z^{(1)}(s)=Z^{(2)}(s)$ para toda $s\in [0,t]$, $c.s$. Definimos

$$
A_n:=\left\{\omega: Z^{(1)}(s,\omega)=Z^{(2)}(s,\omega)\ \text{para todo} s\in [0,n]\right\}.
$$

Sabemos que $\mathbb{P}(A_n)=1$ para toda $n\in \mathbb{N}$ y también

$$
    A = \bigcap_{n=1}^\infty A_n = \left\{ \omega : Z^{(1)}(t,\omega) = Z^{(2)}(t,\omega) \text{ para todo } t \geq 0 \right\}.
$$

Por la continuidad de la probabilidad (propiedad de medidas):

$$
\mathbb{P}(A) = \mathbb{P}\left( \bigcap_{n=1}^\infty A_n \right) = 1.
$$

Veamos el caso cuando $\mathbb{E}[|Z_0|^2]=\infty$. En teoria de probabilidad, al truncar una variable aleatoria podemos cortarla cuando esta está fuera de un rango finito, reemplazando sus valores extremos por cero o por el valor de dicho borde. Vamos aproximar $Z_0$ por una sucesión de variables acotadas, para más adelante garantizar la existencia y unicidad de una solución a la @eq-sde. Definimos el truncamiento de la variable aleatoria $Z_0$ de la forma

$$
    Z_0^{(n)}:=Z_0\cdot 1_{\{|Z_0|\leq n\}},
$$

Donde

$$
1_{\{ |Z_0| \leq n \}}(\omega) =
\begin{cases}
1, & \text{si } |Z_0(\omega)| \leq n, \\
0, & \text{si } |Z_0(\omega)| > n.
\end{cases}
$$

Esto implica que

$$
    Z_0^{(n)}(\omega) = 
    \begin{cases}
    Z_0(\omega), & \text{si } |Z_0(\omega)| \leq n, \\ 
    0, & \text{si } |Z_0(\omega)| > n.
    \end{cases}
$$

Esto garantiza que $\mathbb{E}[|Z_0^{(n)}|^2]\leq n^2<\infty$, por otro lado, cómo $Z_0$ es $\mathbfcal{F}$- medible y $1_{\{|Z_0|\leq n\}}$ también lo es, entonces $Z_0^{(n)}$ es $\mathcal{F}$-medible.

Fijemos $\omega\in \Omega$ tal que $|Z_0(\omega)|<\infty$, por tanto, existe $N\in \mathbb{N}$ tal que $|Z_0(\omega)|\leq N$, de aquí, para todo $n\geq N$, se tiene $|Z_0(\omega)|\leq n$, más aún, $\displaystyle Z_0^{(n)}(\omega)=Z_0(\omega)$. Esto implica que, para casi todo $\omega\in\Omega$, la sucesión $(Z_0^{(n)}(\omega))$ es constante e igual a $Z_0(\omega)$. Así, por definición de convergencia puntual, tenemos

$$
\lim\limits_{n\rightarrow\infty}Z_0^{(n)}(\omega)=Z_0(\omega), \text{ para casi todo $\omega$}.
$$

Por lo tanto

$$
Z_0^{(n)} \xrightarrow[n \to \infty]{\text{c.s.}} Z_0,
$$

entonces para cada $n\in \mathbb{N}$ la variable $Z_0^{(n)}$ es $\mathcal{F}_0$-medible y acotada. Lo que nos permite afirmar que pertenece a $L^2(\Omega,\mathcal{F}_0,\mathbb{P})$. En consecuencia, es posible aplicar los argumentos anteriores, cuando $\mathbb{E}[|Z_0|^2]<\infty$, para afirmar que existe una única solución fuerte de la @eq-sde, digamos $Z^{(n)}$, con condición inicial $Z_0^{(n)}$.

Para cada $N\in \mathbb{N}$, definimos el conjunto

$$
    \Omega_N:=\{\omega\in \Omega:|Z_0(\omega)|\leq N\}.
$$

Esto implica, para cualquier $m>n\geq N$, se tiene

$$
    Z_0^{(m)}(\omega)=Z_0(\omega)=Z_0^{(n)} \text{   para todo $\omega\in \Omega_N$}.
$$ {#eq-20}

Es deicr, en $\Omega_N$, las condiciones iniciales de $Z^{(m)}$ y $Z^{(n)}$ son iguales. Por lo tanto, para todo $t\geq 0$ se cumple que

$$
    Z^{(m)}(t)=Z^{(n)}(t)\ \text{c.s.}
$$

Queremos ver ahora que la sucesión $\{Z^{n}\}_{n\in \mathbb{N}}$ es uniformemente de Cauchy en probabilidad, es decir, dado $\varepsilon>0$ y $\delta>0$, existe $N\in \mathbb{N}$ tal que para todo $m,n\geq N$, se cumple

$$
    \mathbb{P}\Bigg(\sup\limits_{t\geq 0}|Z^{(n)}(t)-Z^{(m)}(t)|>\delta\Bigg)<\varepsilon.
$$

Notemos que de los conjuntos anteriormente definidos, cumplen que $\Omega_N\subset \Omega_{N+1}$. Por otro lado, al ser $Z_0$ una variable aleatoria real, entonces $\mathbb{P}(|Z_0|<\infty)=1$ . Así al ser $\Omega_N$ una sucesión de conjuntos crecientes, se tiene

$$
    \bigcup\limits_{n=1}^{\infty}\Omega_n=\{|Z_0|<\infty\}.
$$

Por la continuidad de la probabilidad, podemos afirmar $\displaystyle \lim\limits_{n\rightarrow \infty}\mathbb{P}(\Omega_n)=1$. Esto implica que para cualquier $\varepsilon>0$, existe $N\in \mathbb{N}$ tal que

$$
    \mathbb{P}(\Omega_N)>1-\varepsilon.
$$ {#eq-21}

De @eq-20 sabemos que

$$
\sup\limits_{t\geq 0}|Z^{(n)}(t)-Z^{(m)}(t)|=0\ \ \text{en $\Omega_N$}
$$

Por lo tanto, si la diferencia es distinta de cero, es decir, para $\delta>0$, solo puede ocurrir fuera de $\Omega_N$, esto es, ocurre en el complemento de $\Omega_N$. Entonces

$$
\Bigg\{\omega:\sup\limits_{t\geq 0}|Z^{(n)}(t)-Z^{(m)}(t)|>\delta\Bigg\}\subset \Omega_N^{c}.
$$

Por propiedad básica de la probabilidad, podemos afirmar

$$
\mathbb{P}\Bigg(\sup\limits_{t\geq 0}|Z^{(n)}(t)-Z^{(m)}(t)|>\delta\Bigg)\leq\mathbb{P}(\Omega_N^c).
$$

Más aún, notemos que $\mathbb{P}(\Omega_N^c)=1-\mathbb{P}(\Omega_N)$, por la @eq-21, entonces $\mathbb{P}(\Omega_N^c)<\varepsilon$. De la ecuación anterior, podemos afirmar $$
    \mathbb{P}\Bigg(\sup\limits_{t\geq 0}|Z^{(n)}(t)-Z^{(m)}(t)|>\delta\Bigg)<\varepsilon, \ \ \forall\ m,n\geq N
$$

Por lo tanto, la sucesión $(Z^{(n)})_{n\in \mathbb{N}}$ es uniformemente de Cauchy en probabilidad. Al estar en $L^2$ podemos afirmar que existe un proceso $Z=\{Z(t)\}_{t\geq 0}$ de tal forma que

$$
    \sup\limits_{t\geq 0}|Z^{(n)}(t)-Z(t)| \xrightarrow[n \to \infty]{\mathbb{P}} 0.
$$

Por el teorema de convergencia de sucesiones de Cauchy en probabilidad, para la sucesión es posible extraer una subsucesión $\{Z_{n_k}\}$ tal que se cumple

$$
    \sup\limits_{t\geq 0}|Z^{(n_k)}(t)-Z(t)| \xrightarrow[k \to \infty]{\text{c.s.}} 0.
$$

De aquí, notemos que por construcción, cada $Z^{(n_k)}$ posee trayectorias càdlàg, y la convergencia es uniforme casi segura, entonces el límite $Z$ admite una versión càdlàg. Por otro lado, dado que cada $Z^{(n_k)}$ es adaptado y su convergencia al proceso $Z$ es uniforme, basta notar que la adaptabilidad de un proceso se converva bajo convergencia puntual, en nuestro caso, convergencia uniforme casi seguramente, por tanto podemos afirmar que el límite $Z$ es adaptado.

Analicemos ahora la unicidad de dicha solución. Procediendo por contradicción, supongamos que existe otra solución fuerte $Z'=(Z'(t))_{t\geq 0}$ con la misma condición inicial $Z_0$. Fijando a $N\in \mathbb{N}$, consideremos al conjunto $\Omega_N$, ya sabemos que en este conjunto la condición incial es acotada y además por el caso $\mathbb{E}[|Z_0|^2]<\infty$ la solución es única. Por lo tanto

$$
    Z'(t)(\omega) = Z_M(t)(\omega)\ \ \ \  \text{para todo }t\geq 0,\ \ \ \ \ \forall\omega\in \Omega_N\ \text{c.s.}
$$

para cualquier $M\geq N$, donde $Z_M$ es la solución con condición inicial truncada $Z^{(M)}=Z_0$ en $\Omega_N$. Asumamos que esto falla para algún $M\geq N$, es decir, existe un conjunto $A\subset \Omega_N$ con $\mathbb{P}(A)>0$ tal que $Z'(t)(\omega)\neq Z_M(t)(\omega)$ con $\omega\in A.$ Podemos definir un nuevo proceso, llamemos a este $Z''_M$, mediante

$$
Z''_M(t)(\omega) =
\begin{cases}
Z'(t)(\omega), & \omega\in A, \\
Z_M(t)(\omega) & \omega\notin A.
\end{cases}    
$$

Dado que $A\subset \Omega_N$, entonces $A\in \mathcal{F}_0$, podemos afirmar que $Z''$ es adaptado, pues $Z'$ y $Z^{(M)}$ son dos procesos adaptados en un conjunto $\mathcal{F}_0$-medible. Luego, al ser $Z''$ la combinación de dos funciones càdlàg entonces $Z''$ es càdlàg.

Notemos que si $\omega\in A\subset \Omega_N\subset \Omega_M$, entonces

$$
    Z''_M(0)(\omega)=Z'(0)(\omega)=Z_0(\omega)=Z_0^{(M)}(\omega),
$$

por otro lado, si $\omega\notin A$, esto implica que

$$
    Z''_M(0)(\omega)=Z^{(M)}(0)(\omega)=Z_0(\omega),
$$

en ambos casos se tiene que $Z''_M(0)=Z^{(M)}(0)$ con $\omega\in A$ casi seguramente.

Entonces $Z''_M$ y $Z^{(M)}$ son dos soluciones de la @eq-sde con la misma condición inicial, por construcción, en el conjunto $A$, se tiene que $Z''_M(t)\neq Z^{(M)}(t)$ para algún $t$. Lo cual es una contradicción al caso cuando $\mathbb{E}[|Z_0|^2]<\infty$ donde se establece la unicidad casi segura de la solución fuerte.

Dado que al suponer $\mathbb{P}(A)>0$ nos lleva a una contradicción, podemos afirmar que $\mathbb{P}(A)=0$, es decir, $Z'(t)=Z^{(M)}(t)$ para todo $t\geq 0$, casi seguramente en $\Omega_N$. Esto vale para todo $N\in \mathbb{N}$, como

$$
    \mathbb{P}\Bigg(\bigcup\limits_{N=1}^{\infty}\Omega_N\Bigg)=1,
$$

podemos concluir

$$
    \mathbb{P}(Z'(t)=Z(t)\ \text{para todo }\ t\geq 0)=1.
$$

Por lo tanto, la solución fuerte es única casi seguramente
:::